apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: clamav-db-hermetic
  namespace: rhtap-integration-tenant
  annotations:
    # This annotation tells Konflux to set up the webhooks for this repository.
    build.appstudio.openshift.io/request: configure-pac
  labels:
    appstudio.openshift.io/application: konflux-clamav
    appstudio.openshift.io/component: clamav-db-hermetic
    pipelines.appstudio.openshift.io/type: build
spec:
  application: konflux-clamav
  componentName: clamav-db-hermetic
  source:
    git:
      url: https://github.com/konflux-ci/konflux-clamav.git
      context: ./
